language: node_js
node_js:
  - '8.9'
  - '10'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g 'npm@>=5'
after_success:
  - npx nyc report --reporter=text-lcov | npx coveralls
before_deploy:
  - npm run build
deploy:
  - provider: npm
    tag: "$NPM_TAG"
    skip_cleanup: true
    email: ops@craft.ai
    api_key:
      secure: PW+IEuPvBx0BBRTkbelWg3WwvYzrZNKkdIiaOX940sOUAHPcALCp7wx4hdkrmBFpUtRlDkpdSMELH39R6R+mRoe+if4gExkObKXA8KepElkXgKA6UhzvXItkXk8JW8fw3k64ktNygIrdQjxaq2rwO7V10HBEMHCQY1XHSm3bX38iCaHbMqjDs+UXD1mlSivzYSV5qvbGL4vnVeIiCb2uApKwRQJbiJv6x8s6SO6xArYfoyFcpiUFZI9XQrL3XNtw4da4VbQ+tct5TPosbhEQSZ984m37otpxeJzd+fvIJetBwiKb9FcAo4FWF4ZGpam+IleVp2kO+Zojn5IGZ1gv/OiDLu8PZErWECEKKEPz6usgfCY5lpPmg0czgbNyUg4MwZq4HxnxVEfyjkENaQXsvGhUY3aYfc/9l9nVpf3pgkg1e0gVsdw84kEzwhDm31wZeW0CmDvCNkvCCEX2ZgwXOerM9toiYyvGaXIdFKjNAc6ElJeEd6yqzBTbPbhh67lFbnGhDUfHZlf/Bs01HMGMG8TM6D+csKssRgAGt+0e4DupYmW2K04kq6cWXkQLoCekg0Xdv52NUhgqLA4lZwGSEnes0X0IvWF5/NA4P+YnIx8K/4t8PUzCiL0bcyDIQ8BXrDcbdzGzpUj9ytP+iTHeUQ6I2Szc0k22z1dBOxjxzKQ=
    on:
      repo: craft-ai/craft-ai-kit-energy
      all_branches: true
      condition: '"$TRAVIS_TAG" =~ ^v[0-9]'
      node: '6.9'
notifications:
  slack: craft-ai:ZNnQErHJhw40oKmphy3fNGza
  email: ops@craft.ai
env:
  global:
    - NPM_TAG=$([[ "$TRAVIS_TAG" == *-* ]] && echo 'next' || echo 'latest')
    - secure: h4DkJhRYgg4hUl49YT23R7iVY5T4ukVlMM6TaYeojXknFySPSbPhU6IS/5fH5goJvXgVoj4XjL1qqD8nIzPEgYwkKI3Tui3+tPjQ8G09qDFX/ENdwuAsRkjqa7+2yJBjG5X0COPC0mep4sTJGidnVzcrq92DTwqDp/sNFEuODYNp6v2ZvjjbScXpiQjMwzA6aeFszjwWP0DPK4c1y/JuNKF3NHr7f6GdbNX2IQb/pAi0R4ZPqnthVEZnXlkjPPA/Rq8naGlUum79CDED5iW86c0cF5CAKPnFaO15MazdTWfEB2gmtr60B33m6bpoPO7esHl5PP2r/nvnOfQgOQ7n7bzmVbxHbImOFebojEda+2g63FgWXRAbCVJh29iSNETPACx5ihWgDbpZBgsO0rI1m56Ymg2z8qwhYpzlyu+Z4Omwr+TiCIB7CM+d9AMKxprliItvRPVjQyXiYCKSUBskOfl5F1zIV3aKiZR6wxEzvWC+ylVNyxBrYAZw9YcLmFM1Y52UmtzEgfxlTYWTS4fMQTH33a+uOfZcVRLFYaUnPCjMSBsrmaJ+1IQ+uHjvCA/IXeuGjJfbxdA506RoAsFEAxgc6DPSZJi2sm1Xdv//CVyVZecRHvY2SFHDkXFCR6yi0NNTGrhL/+JxsnauXyPG/AHkrlOeBkwGa/MF0xulS3A=
