name: test kit energy
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Preparing test/build environment 
      - name: Checkout scm
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "10.x"
          registry-url: 'https://registry.npmjs.com'
      - name: Install packages
        run: npm install
      - name: Run test
        run: npm test
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: run_tests
    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9] ]]; then
              echo ::set-output name=match::true
          fi
      - name: Checkout scm
        if: steps.check-tag.outputs.match == 'true'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Node
        if: steps.check-tag.outputs.match == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: "10.x"
          registry-url: 'https://registry.npmjs.com'
      - name: Install packages
        if: steps.check-tag.outputs.match == 'true'
        run: npm install
      - name: Packaging & release
        if: steps.check-tag.outputs.match == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.CRAFT_AI_NPM_TOKEN }}
          tag: ${{ steps.tag_or_latest.outputs.tag }}
      - name: Send message to Slack API
        if: steps.check-tag.outputs.match == 'true'
        uses: archive/github-actions-slack@v1.0.3
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ci
          slack-text: Success! Github Actions for ${{ github.head_ref }} ("https://github.com/${{ github.repository }}/actions")