name: test js client
on:
  push:
    tags:
      - '^v[0-9]'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Preparing test/build environment 
      - name: Checkout scm
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "10.x"
          registry-url: 'https://registry.npmjs.com'
      - name: Install packages
        run: yarn install
      - name: Tag or latest
        id: tag_or_latest
        run: |
          if [[ ${{ github.event.ref }} ~= *-* ]]
          then
              echo "::set-output name=tag::next"
          else
              echo "::set-output name=tag::latest"
          fi
        env:
          REF: ${{ github.ref }}
      - name: Packaging & release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.CRAFT_AI_NPM_TOKEN }}
          tag: ${{ steps.tag_or_latest.outputs.tag }}
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v1.0.3
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ci
          slack-text: Success! Github Actions for ${{ github.head_ref }} ("https://github.com/${{ github.repository }}/actions")
